name: Backups

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  update:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Connects to VPS via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOYER_CI_IP_ADDRESS }}
          port: ${{ secrets.DEPLOYER_CI_PORT }}
          username: ${{ secrets.DEPLOYER_CI_USER_NAME }}
          key: ${{ secrets.DEPLOYER_CI_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEPLOYER_CI_PRIVATE_KEY_PASSWORD }}
          script: |
            cd joegatt.net-server
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa_deploykey_unsigned
            ./aphroconfuso-daily-tasks.sh
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C08TQEMC3\",\"text\":\"aphroconfuso.mt backups status: ${{ job.status }}\"}'
